LANGUAGES = {
    "pl": {
        "title": "Logic BlastSolver - rozwiązywanie wyrażeń logicznych",
        "description": "Wprowadź wyrażenie logiczne ręcznie lub wybierz jedno z predefiniowanych zdań.",
        "choose_tautology": "Lub wybierz tautologię z listy:",
        "input_expression": "Wprowadź własne wyrażenie logiczne:",
        "solve_button": "Rozwiąż wyrażenie",
        "ota_solver": "Rozwiązanie za pomocą OTA Solver",
        "blast_solver": "Rozwiązanie za pomocą BlastBit Solver",
        "logic_tree": "Drzewo logiczne",
        "error": "Błąd podczas rozwiązywania wyrażenia",
        "correct_expression": "Wyrażenie logiczne jest poprawne!",
        "none": "Brak",
        "solved_in": "rozwiązano w",
        "no_results": "Brak wyników do wyświetlenia.",
        "tautology": "Tautologia",
        "contradiction": "Sprzeczność",
        "logic_tree_error": "Błąd podczas generowania drzewa logicznego: ",
        "statistics_found": "Znaleziono",
        "statistics_results": "rozwiązania(-e)",
        "true_results": "Prawda",
        "false_results": "Fałsz",
        "and": "oraz",
        "solver_selection": "Wybór solverów",
        "timeout_setting": "Ustaw timeout (w sekundach)",
        "timeout_label": "Timeout solvera",
        "timeout_error": "Solver przekroczył timeout {timeout} sekund.",
        "solving": "Rozwiązywanie",
    },
    "en": {
        "title": "Logic BlastSolver - solving logical expressions",
        "description": "Enter a logic expression manually or select one from predefined sentences.",
        "choose_tautology": "Or choose a tautology from the list:",
        "input_expression": "Enter your own logical expression:",
        "solve_button": "Solve Expression",
        "ota_solver": "Solution using OTA Solver",
        "blast_solver": "Solution using BlastBit Solver",
        "logic_tree": "Logic Tree",
        "error": "Error while solving the expression",
        "correct_expression": "The logical expression is correct!",
        "none": "None",
        "solved_in": "solved in",
        "no_results": "No results to display.",
        "tautology": "Tautology",
        "contradiction": "Contradiction",
        "logic_tree_error": "Error generating logic tree: ",
        "statistics_found": "Found",
        "statistics_results": "results",
        "true_results": "True",
        "false_results": "False",
        "and": "and",
        "solver_selection": "Solver selection",
        "timeout_setting": "Set Timeout (in seconds)",
        "timeout_label": "Solver Timeout",
        "timeout_error": "The solver exceeded the timeout of {timeout} seconds.",
        "solving": "Solving",
    }
}